name: Build Application

on:
  push:
    branches:
      - master
      - release/*
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Add uv to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Create virtual environment and install dependencies
        run: | 
          uv venv
          source .venv/bin/activate
          uv sync
      - name: Build with PyInstaller
        run: | 
          source .venv/bin/activate
          pyinstaller HDMI_Matrix_Control.spec
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: HDMI-Matrix-Control-linux
          path: dist/"HDMI_Matrix_Control"

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install uv
        run: | 
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Create virtual environment and install dependencies
        run: | 
          uv venv
          .venv\Scripts\activate
          uv sync
      - name: Build with PyInstaller
        run: | 
          .venv\Scripts\activate
          pyinstaller HDMI_Matrix_Control.spec
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: HDMI-Matrix-Control-windows
          path: dist/"HDMI_Matrix_Control.exe"

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Add uv to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Create virtual environment and install dependencies
        run: | 
          uv venv
          source .venv/bin/activate
          uv sync
      - name: Build with PyInstaller
        run: | 
          source .venv/bin/activate
          pyinstaller HDMI_Matrix_Control.spec
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: HDMI-Matrix-Control-macos
          path: dist/"HDMI_Matrix_Control"
