name: Build Application

on:
  push:
    branches:
      - master
      - release/*
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
      - name: Install xcb libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libxcb-keysyms1 libxcb-image0 libxcb-render-util0 libxcb-xinerama0 libxcb-icccm4 libxcb-randr0 libxcb-sync1 libxcb-xfixes0 libxkbcommon0  libxkbcommon-x11-0 libxcb-shape0 libxcomposite-dev libxcomposite1 libx11-xcb-dev libxcb-xkb-dev libxkbfile-dev libx11-dev
      - name: Install dependencies
        run: | 
          uv sync
      - name: Build with PyInstaller
        run: | 
          source .venv/bin/activate
          pyinstaller HDMI_Matrix_Control.spec
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: HDMI-Matrix-Control-linux
          path: dist/HDMI_Matrix_Control

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
      - name: Create virtual environment and install dependencies
        run: | 
          uv venv
          .venv\Scripts\activate
          uv sync
      - name: Build with PyInstaller
        run: | 
          .venv\Scripts\activate
          pyinstaller HDMI_Matrix_Control.spec
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: HDMI-Matrix-Control-windows
          path: dist/HDMI_Matrix_Control.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
      - name: Install dependencies
        run: | 
          uv sync
      - name: Build with PyInstaller
        run: | 
          source .venv/bin/activate
          pyinstaller build_macos.spec
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: HDMI-Matrix-Control-macos
          path: "dist/HDMI Matrix Control.app"
